### ISSUE TITLE
Napari widget should work for nD images

### ISSUE THREAD

**Issue by quantumjot** [lowe-lab-ucl/cnn-annotator#4]
Currently only works for 2d time-lapse, but we should be able to export 3d time-lapse, multichannel data.  Need to update `get_image_patches` to enable this.

**Comment by KristinaUlicna** [comment]
Hi all, I modified the `get_image_patch` function so that it can slice a patch from the original images in nD setting. It's current output is `patch = [[np.array(... ...)], False]` where `patch[0]` is a list of `np.arrays` corresponding to the length of layers - say, if one had a movie dataset of BF + GFP + RFP time-lapse, it would crop 3 `np.arrays` around the specified coordinate. The `patch[1]` is a `boolean` where `True` means the patch is flagged (i.e. 0s padding included in the patch edges). 

The question remains on how to organise such nD patches in the zip file tree. Currently, we have an organisation of `/annotation_XXX.json` and `/Interphase/Interphase_XXX.tif` with the tif image files in the subdirectories corresponding to the labels. How would you like to store these images so it's easy to import them for training? 

+ Divide into subdirectories such as `/Interphase/BF/Interphase_XXX.tif` and `/Interphase/GFP/Interphase_XXX.tif` and  `/Interphase/RFP/Interphase_XXX.tif` ... 
+ Would you prefer the patch tif file to have the channel name in it? Such as "Interphase_**GFP**_03-08-2021--13-39-57_0.tif" and `Interphase_**RFP**_03-08-2021--13-39-57_0.tif` and have them in the one folder?
+ Or both?

@chris-soelistyo @laureho @quantumjot what are your suggestions?

**Comment by quantumjot** [comment]
The tiff format can save multidimensional arrays. So, you could make the output patch be three dimensional (i.e. Y, X, C by stacking the channels along last axis). If you do that, nothing else has to change in the code, except perhaps storing the explicit ordering of the channels in the json file, for future reference.
